config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "g#index"
  
  get 'g/user/:id(.:format)', to: 'g#user'
  put "post/:id/like", to: "posts#like", as: "like"
  put "post/:id/unlike", to: "posts#unlike", as: "unlike"
  get "g/user"
  get "admin", to: "admin#all"
  resources :posts
  resources :users
  resources :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
	validates :user_id, presence: true
	validates :content, presence: true, length: {minimum: 1}

	belongs_to :user
	has_many :likes, dependent: :destroy

	def liked?(user)
		Like.where(user_id: user.id, post_id: self.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login, :pfp
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :pfp, PfpUploader

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {
      value: login.strip.downcase
    }]).first
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def all
		if user_signed_in? && current_user.username=="kamtr_official"
			@users=User.all
		else
			redirect_to g_user_path, alert: "Haha, nice try!"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_in, keys:[:login,:password])
			devise_parameter_sanitizer.permit(:sign_up, keys:[:username,:name,:date_of_birth,:description,:email])
			devise_parameter_sanitizer.permit(:account_update, keys:[:username,:name,:date_of_birth,:description, :pfp])
		end
end

app/controllers/g_controller.rb
class GController < ApplicationController
	def index
		@posts = Post.limit(20).order("created_at DESC")
	end

	def user

		unless params[:id] == nil
			@user = User.find_by(username: params[:id])
			redirect_to g_user_path, alert: "No user with that ID exists!" if @user == nil 	
		else
			@user = user_signed_in? ? current_user : User.find_by(username: "kamtr_official")
		end

		@posts = user_posts!
	end

	private

	def user_posts!
		Post.where(user_id: @user.id).order("created_at DESC") unless @user == nil
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to g_user_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to root_path, status: :see_other
    end

    def like
        @post = Post.find(params[:id])
        Like.create(user_id:current_user.id, post_id: @post.id)
        redirect_back(fallback_location: root_path)
    end
    
    def unlike
        @like = Like.where(post_id: params[:id],user_id: current_user.id).first
        @like.destroy
        redirect_back(fallback_location: root_path)
    end

    private
    def post_params
        params.require(:post).permit(:user_id,:content,:is_edited)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def destroy
		if user_signed_in? && current_user.username=="kamtr_official"
			@user = User.find(params[:id])
	    	@user.destroy
	    	redirect_to root_path, status: :see_other
		else
			redirect_to g_user_path, alert: "Not nice!"
		end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/all.html.erb
<% @users.each do |i| %>
  <div class=" card card-body">
    <%= i.username %><br/>
    <%= i.email %><br/>
    <%= link_to "Delete this account!",user_path(i), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
  <br/>
<% end %>

app/views/g/_like_button.html.erb
<% if user_signed_in? %>
	<%unless post.liked?(current_user)%>
		<%= button_to "#{Like.where(post_id: post.id).count}♡", like_path(post), method: "put", class:"btn",style:"margin-right: 0"%>
	<% else %>
		<%= button_to "#{Like.where(post_id: post.id).count}♥", unlike_path(post), method: "put", class:"btn",style:"margin-right: 0"%>
	<%end%>
<% else %>
	<%= button_to "#{Like.where(post_id: post.id).count}♡", like_path(post), method: "put", class:"btn",style:"margin-right: 0", disabled: true%>
<% end %>

app/views/g/_poster.html.erb
<% @posts.each do |i| %>
	<% @local_user = i.user %>
	<div class="card" style="width: 40rem; margin-left:auto;margin-right: auto;">
  		<div class="card-body row row-cols-2">
    		<div class="col col-md-3" style="text-align: center;">
    			<% puts @local_user.pfp%>
    			<%= image_tag @local_user.pfp.url != nil ? @local_user.pfp_url : "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",alt: "...",size:"64x64" %>
    		</div>

    		<div class="col col-md-9">
    			<p class="card-text"><%= i.content%></p>
    		</div>

    		<div class="col col-md-3" style="text-align: center;margin-top: 0.5rem;">
	    		<h6 class="card-subtitle mb-2 text-muted">
	    			<%= link_to "@"+@local_user.username, g_user_path(:id => @local_user.username),class:"link-secondary text-decoration-none" %>
	    		</h6>
    		</div>

    		<div class="col col-md-8" style="text-align: right;">
    			<%= i.created_at.strftime("Posted on %d.%m.%Y %H:%M") %>			
    		</div>

    		<div class="col col-md-1">
    			<%= render "g/like_button", post: i, style:"margin-right: 5%;"%>
    		</div>

    		<%if user_signed_in? && (current_user.id==i.user_id || current_user.username=="kamtr_official")%>
				<%= link_to "<delete>", post_path(i), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-decoration-none"%>
			<% end %>

  		</div>
	</div>
	<br>
<% end %>

app/views/g/_user_card.html.erb
<div class="card col-sm-4 col-2 fixed-top" style="width: 16.65%; margin-top: 8rem; margin-left: 3rem;">
  	<%= image_tag @user.pfp.url != nil ? @user.pfp_url : "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",alt: "...",size:"294x294",style:"margin-top:0.75rem"%>

  	<div class="card-body">
                <h5 class="card-title">
                	<%= "@"+@user.username%>
                </h5>

                <div class="card-text">
                	<%= @user.name%> <br>
                	Born on <%= @user.date_of_birth.strftime("%eth of %B, %Y")%>
                	<hr>
                	<%= @user.description%>
                </div>
  	</div>
</div>

app/views/g/index.html.erb
<div style="text-align:center">
	<h1>Welcome to Kamtr</h1>
	<h2>Latest posts</h2>
</div>
<%= render "g/poster"%>
<%= link_to "TO USER","g/user" %>

app/views/g/user.html.erb
<div class="container">
  <div class="row">
  	<%= render "g/user_card"%>
    <div class="col-sm-8 offset-sm-2">
    	<%= render "g/poster" %>
    	<%= link_to "TO INDEX",root_path %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #98c8eb;">
  <div class="container-fluid">
    <%= link_to "Kamtr", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="navbar-nav">
        <% unless user_signed_in?%>
               <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
               <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            <% else %>
                <%if current_user.username == "kamtr_official" %>
                  <%= link_to "Admin Panel", admin_path, class:"nav-link" %>
                <% end %>
                <%= link_to "New Post", new_post_path, class:"nav-link" %>
                <%= link_to "My Posts", g_user_path, class:"nav-link" %>
                <%= link_to "My Account", edit_user_registration_path, class:"nav-link" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :get} , class:"nav-link" %>
            <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Kamtr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body style="margin-top: 4rem;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= render "layouts/header" %>

    <% if notice%>
      <%= render "posts/partials/notice" %>
    <% elsif alert%>
      <%= render "posts/partials/alert" %>
    <% end%>
    
    <%= yield %>
    
  </body>
</html>

app/views/posts/new.html.erb
<h1 style="display: flex;justify-content: center;margin-top: 8rem">New Post:</h1>
<% if user_signed_in? %>

    <%= form_with model: @post do |i| %>

        <%= i.hidden_field :user_id, value:current_user.id %>
        <%= i.hidden_field :is_edited, value: false%>

        <% @post.errors.full_messages_for(:content).each do |message| %>
            <div style="text-align:center;"><%= message %></div>
        <% end %>
        
      	<div class="container" style="display: flex;justify-content: center;margin-top: 2rem;">

          <div class="field form mb-4" style="width: 60%;">
              <%= i.text_area :content, autofocus: true, class:"form-control",id:"cont-field", placeholder: "content", rows:10%>
          </div>
          
        </div>

        <div class="actions", style="text-align:center;">
          <%= i.submit class:"btn-lg btn-primary"%>
        </div>

    <% end %>

<% else %>
  <h2>You need to be signed in to create a post!</h2>
<% end %>

app/views/posts/partials/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert" style="z-index: 1000; position: relative;">
  <%= alert%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/posts/partials/_notice.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert" style="z-index: 1000; position: relative;">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/posts/show.html.erb
<h1><%=User.find_by(Id: @post.user_id).username %></h1>
<p><%= @post.content %></p>
<p><%= @post.is_edited %></p>
<%= link_to "Destroy", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<%= link_to "BACK", g_user_path%>